pool:
  vmImage: 'ubuntu-18.04'

steps:
  - task: ShellScript@2
    displayName: 'Build Docker images'
    inputs:
      scriptPath: 'docker-build.sh'
    env:
      DOCKER_ID: $(DOCKER_ID)
      DOCKER_PASSWORD: $(DOCKER_PASSWORD)