trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - /
    exclude:
    - /README.md
    - /azuredeploy.json

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: ShellScript@2
    displayName: 'Build Docker images'
    inputs:
      scriptPath: 'docker-build.sh'
    env:
      DOCKER_ID: $(DOCKER_ID)
      DOCKER_PASSWORD: $(DOCKER_PASSWORD)